"""add phone and specialization

Revision ID: 40892b6953a9
Revises: da7cef84fc20
Create Date: 2026-06-28 11:49:21.320457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40892b6953a9'
down_revision = 'da7cef84fc20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('specialization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'specialization')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
