"""make medicine_id nullable

Revision ID: da7cef84fc20
Revises: 006_restock_req
Create Date: 2026-06-27 22:25:19.558199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da7cef84fc20'
down_revision = '006_restock_req'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'medicine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.execute("DROP INDEX IF EXISTS ix_order_items_medicine_id")
    op.execute("DROP INDEX IF EXISTS ix_order_items_order_id")
    op.execute(
        "ALTER TABLE order_items DROP CONSTRAINT IF EXISTS order_items_order_id_fkey"
    )
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatus'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::orderstatus"))
    op.alter_column('orders', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.execute("DROP INDEX IF EXISTS ix_orders_user_id")
    op.execute(
        'ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_order_number_key'
    )
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.execute(
        'ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_user_id_fkey'
    )
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.execute(
        'ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_users_email'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_users_email'
    )
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.execute("DROP INDEX IF EXISTS ix_orders_order_number")
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=False)
    op.create_unique_constraint('orders_order_number_key', 'orders', ['order_number'])
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.alter_column('orders', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::orderstatus"))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_medicine_id', 'order_items', ['medicine_id'], unique=False)
    op.alter_column('inventory', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'medicine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
